### ISSUE TITLE
Parser da tabela SLR

### ISSUE THREAD

**Issue by henriquels25** [henriquels25/compiler_slr#2]

**Comment by henriquels25** [comment]
Desenvolvido. 
Mateus, faz uns testes para ver se esta OK.

**Comment by mfelipe-eisenkraemer** [comment]
Pelos testes está ok.

Na gramática 2, quando tento reconhecer '()' os passos pra reconhecer a sentença são:

1- ["0"]
2- ["0", "(", "4"]
3- ["0", "(", "4", ")", "7"]
4- ["0", "P", 8]
5- ["0", "L", 2]
6- ["0", "A", 1]

No passo 3, estando no estado 7, reduziu  P -> (), mas pq empilhou o estado 8 na pilha?

**Comment by henriquels25** [comment]
A pilha estava assim: 3- ["0", "(", "4", ")", "7"]
Ai ele reduziu (), com isso, tirou quatro da pilha, sempre o dobro da produção. Aí ficou no estado 0.
No estado 0, com a entrada P, o goto da tabela é o estado 8.

Deu pra entender?
